apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdp-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdp
  template:
    metadata:
      labels:
        app: hdp
    spec:
      containers:
        - name: hdp
          # Replace $GCLOUD_PROJECT with your project ID
          image: gcr.io/bbk-dev/hdp-gke:1.0.0
          volumeMounts:
            - mountPath: /hdp
              name: hdp-volume
          resources:
            requests:
              cpu: 400m
              memory: 2Gi
            limits:
              cpu: 800m
              memory: 4Gi
      volumes:
        - name: hdp-volume
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: hdp-disk
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hdp
  name: hdp-svc
spec:
  ports:
    - port: 8088
      name: yarn
    - port: 50070
      name: hdfs
  selector:
    app: hdp
  type: NodePort
